files_list = [
    '/data/David/widefield_ALL/TAC_group_7/A_thy1_spont/A_thy1_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/A_thy1_spont/A_thy1_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/A_thy1_spont/A_thy1_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_98_thy1_spont/B_98_thy1_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_98_thy1_spont/B_98_thy1_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_98_thy1_spont/B_98_thy1_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_98_thy1_spont/B_98_thy1_spont_MMStack_Pos0_3.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_400_thy1_spont/B_400_thy1_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_400_thy1_spont/B_400_thy1_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_400_thy1_spont/B_400_thy1_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/B_400_thy1_spont/B_400_thy1_spont_MMStack_Pos0_3.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_24_spont/C_24_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_24_spont/C_24_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_24_spont/C_24_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_24_spont/C_24_spont_MMStack_Pos0_3.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_79_spont/C_79_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_79_spont/C_79_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_79_spont/C_79_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/C_79_spont/C_79_spont_MMStack_Pos0_3.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/D_thy1_spont/D_thy1_spont_MMStack_Pos0.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/D_thy1_spont/D_thy1_spont_MMStack_Pos0_1.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/D_thy1_spont/D_thy1_spont_MMStack_Pos0_2.ome.tif',
    '/data/David/widefield_ALL/TAC_group_7/D_thy1_spont/D_thy1_spont_MMStack_Pos0_3.ome.tif'

]
